export const SEARCH_RESULTS_REQUEST = 'SEARCH_RESULTS_REQUEST';
export const SEARCH_RESULTS_RETRIEVED = 'SEARCH_RESULTS_RETRIEVED';
export const SEARCH_RESULTS_ERROR = 'SEARCH_RESULTS_ERROR';
export const SEARCH_INPUT_LOST_FOCUS = 'SEARCH_INPUT_LOST_FOCUS';
export const SEARCH_INPUT_GAINED_FOCUS = 'SEARCH_INPUT_GAINED_FOCUS';
export const SEARCH_ITEM_CLICKED = 'SEARCH_ITEM_CLICKED';
